# Generated by Django 4.2.7 on 2025-10-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название бренда')),
                ('logo', models.ImageField(upload_to='brands/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL slug')),
                ('icon', models.FileField(blank=True, null=True, upload_to='categories/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL slug')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Изображение')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, upload_to='services/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL slug')),
                ('logo', models.ImageField(upload_to='tenants/logos/', verbose_name='Логотип')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='tenants/covers/', verbose_name='Обложка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('floor', models.CharField(max_length=50, verbose_name='Этаж')),
                ('location_on_map', models.CharField(blank=True, max_length=200, verbose_name='Местоположение на карте')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('website_url', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('operating_hours', models.TextField(blank=True, help_text='Например: Пн-Чт: 10:00-23:00, Пт-Вс: 10:00-00:00', verbose_name='Часы работы')),
                ('has_promotions', models.BooleanField(default=False, verbose_name='Акции и скидки')),
                ('has_loyalty_program', models.BooleanField(default=False, verbose_name='Программа лояльности')),
                ('is_temporarily_closed', models.BooleanField(default=False, verbose_name='Временно закрыто')),
                ('has_delivery', models.BooleanField(default=False, verbose_name='Доставка')),
                ('has_business_lunch', models.BooleanField(default=False, verbose_name='Бизнес-ланч')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='core.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='core.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Арендатор',
                'verbose_name_plural': 'Арендаторы',
                'ordering': ['name'],
            },
        ),
    ]
